language: node_js

os: osx

notifications:
  email: false
  
node_js:
  - 12

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

defaults: &defaults
  script:
    #   ## print all Travis environment variables for debugging
    - npm run start
    - npm run cy:run
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true

jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
    # run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
